package dev.woge.ksp

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test

class ActionProcessorTest {
    @Test
    fun `native upload descriptors preserve their multipart type and validate underlying form fields`() {
        val wrapped = VALID.replace("command: CreateTask", "command: MultipartSubmission<CreateTask>")
        val result = runKsp(mapOf("Upload.kt" to source(wrapped)))
        assertEquals(emptyList<String>(), result.errors)
        assertTrue(
            result.generated
                .getValue("CreateTaskAction.kt")
                .contains("ActionDescriptor<dev.woge.host.MultipartSubmission<shop.CreateTask>>"),
        )
        assertTrue(
            result.generated
                .getValue("WogeDescriptors.kt")
                .contains("dev.woge.host.MultipartSubmission<shop.CreateTask>"),
        )
        val unsupported = runKsp(mapOf("Upload.kt" to source(wrapped).replace("val title: String", "val title: Any")))
        assertTrue(unsupported.errors.any { it.contains("WOGE-ACTION-003") })
        val hidden =
            runKsp(
                mapOf(
                    "Upload.kt" to source(wrapped).replace("data class CreateTask", "internal data class CreateTask"),
                ),
            )
        assertTrue(hidden.generated.getValue("CreateTaskAction.kt").contains("internal object CreateTaskAction"))
    }

    @Test
    fun `nullable star and nested multipart command shapes are rejected`() {
        for (type in listOf(
            "MultipartSubmission<CreateTask>?",
            "MultipartSubmission<CreateTask?>",
            "MultipartSubmission<*>",
            "MultipartSubmission<out CreateTask>",
            "MultipartSubmission<in CreateTask>",
            "MultipartSubmission<MultipartSubmission<CreateTask>>",
        )) {
            val result = runKsp(mapOf("Upload.kt" to source(VALID.replace("command: CreateTask", "command: $type"))))
            assertTrue(result.errors.any { it.contains("WOGE-ACTION-003") }, result.errors.toString())
        }
    }

    @Test
    fun `generates typed action and deterministic explicit registry`() {
        val result = runKsp(mapOf("Actions.kt" to source(VALID)))
        assertEquals(emptyList<String>(), result.errors)
        assertEquals(setOf("CreateTaskAction.kt", "WogeActions.kt", "WogeDescriptors.kt"), result.generated.keys)
        assertEquals(
            """
            // Generated by the Woge KSP processor from @WogeAction createTask. Do not edit.
            package shop

            /** Typed entry point for the native form action `create-task`. */
            public object CreateTaskAction : dev.woge.host.ActionDescriptor<shop.CreateTask>(dev.woge.host.ActionId.of("create-task")) {
                override suspend fun execute(request: dev.woge.host.PageRequest<shop.CreateTask>): dev.woge.host.PageResult =
                    shop.createTask(request.input, request.context)
            }

            """.trimIndent(),
            result.generated.getValue("CreateTaskAction.kt"),
        )
        assertEquals(
            RecordedDependencies(true, listOf("Actions.kt")),
            result.dependencies.getValue("WogeActions.kt"),
        )
        assertEquals(result.generated, runKsp(mapOf("Actions.kt" to source(VALID))).generated)
    }

    @Test
    fun `rejects unsupported action shapes with located rules`() {
        INVALID.forEach { (rule, action) ->
            val result = runKsp(mapOf("Actions.kt" to source(action)))
            assertTrue(
                result.errors.any { it.contains(rule) && it.startsWith("Actions.kt:") },
                result.errors.toString(),
            )
        }
    }

    @Test
    fun `duplicate public IDs across packages fail before a registry is usable`() {
        val result =
            runKsp(
                mapOf(
                    "Actions.kt" to source(VALID),
                    "Other.kt" to source(VALID).replace("package shop", "package other"),
                ),
            )
        assertEquals(2, result.errors.count { it.contains("WOGE-ACTION-007") })
        assertEquals(emptyMap<String, String>(), result.generated)
    }

    @Test
    fun `registry is sorted by ID and follows command source dependencies`() {
        val result =
            runKsp(
                mapOf(
                    "Actions.kt" to
                        source(
                            VALID + "\n" +
                                VALID.replace("create-task", "archive-task").replace("createTask", "archiveTask"),
                        ),
                ),
            )
        assertEquals(emptyList<String>(), result.errors)
        assertTrue(result.generated.getValue("WogeActions.kt").contains("listOf(ArchiveTaskAction, CreateTaskAction)"))
    }

    @Test
    fun `command file changes are tracked and internal commands keep registry internal`() {
        val result =
            runKsp(
                mapOf(
                    "Command.kt" to "package shop\ninternal data class CreateTask(val title: String)",
                    "Action.kt" to "package shop\nimport dev.woge.host.*\n" +
                        "import dev.woge.html.applicationUrl\n" + VALID.replace("suspend fun", "internal suspend fun"),
                ),
            )
        assertEquals(emptyList<String>(), result.errors)
        assertEquals(
            RecordedDependencies(true, listOf("Action.kt", "Command.kt")),
            result.dependencies.getValue("CreateTaskAction.kt"),
        )
        assertEquals(result.dependencies["CreateTaskAction.kt"], result.dependencies["WogeActions.kt"])
        assertTrue(result.generated.getValue("CreateTaskAction.kt").contains("internal object CreateTaskAction"))
        assertTrue(result.generated.getValue("WogeActions.kt").contains("internal val wogeActions"))
    }

    @Test
    fun `unsupported command fields and duplicate descriptor names fail the build`() {
        listOf("Any", "Map<String, String>", "List<List<String>>").forEach { type ->
            val result = runKsp(mapOf("Actions.kt" to source(VALID).replace("val title: String", "val title: $type")))
            assertTrue(result.errors.any { it.contains("WOGE-ACTION-003") }, result.errors.toString())
        }
        val duplicate =
            runKsp(
                mapOf("Actions.kt" to source(VALID + "\n" + VALID.replace("create-task", "another-task"))),
            )
        assertEquals(2, duplicate.errors.count { it.contains("WOGE-ACTION-007") })
    }

    @Test
    fun `form primitives and their value classes are accepted without route codecs`() {
        val command =
            """
            @JvmInline value class Amount(val value: Double)
            data class CreateTask(
                val title: String, val ratio: Float, val amount: Amount,
                val tiny: Byte, val small: Short, val letter: Char, val amounts: List<Double>,
            )
            """.trimIndent()
        val result =
            runKsp(
                mapOf(
                    "Actions.kt" to
                        source(VALID).replace(
                            "data class CreateTask(val title: String, val labels: List<String> = emptyList())",
                            command,
                        ),
                ),
            )
        assertEquals(emptyList<String>(), result.errors)
        assertTrue(result.generated.containsKey("CreateTaskAction.kt"))
    }

    private fun source(action: String): String =
        """
        package shop

        import dev.woge.host.*
        import dev.woge.html.applicationUrl

        data class CreateTask(val title: String, val labels: List<String> = emptyList())

        $action
        """.trimIndent()

    private companion object {
        val VALID =
            """
            @WogeAction("create-task")
            suspend fun createTask(command: CreateTask, context: RequestContext): PageResult =
                redirect(applicationUrl("/tasks"))
            """.trimIndent()
        val INVALID =
            listOf(
                "WOGE-ACTION-001" to VALID.replace("suspend ", ""),
                "WOGE-ACTION-002" to VALID.replace("create-task", "java.lang.Runtime.exec"),
                "WOGE-ACTION-003" to VALID.replace("command: CreateTask", "command: Any"),
                "WOGE-ACTION-004" to VALID.replace("context: RequestContext", "context: String"),
                "WOGE-ACTION-005" to
                    VALID
                        .replace(
                            ": PageResult",
                            ": String",
                        ).replace("redirect(applicationUrl(\"/tasks\"))", "\"bad\""),
                "WOGE-ACTION-006" to VALID.replace("suspend fun", "private suspend fun"),
            )
    }
}
