package dev.woge.ksp

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class RegionProcessorTest {
    @Test
    fun `page region generates a descriptor that calls the function`() {
        val result =
            runKsp(
                mapOf(
                    "Summary.kt" to
                        """
                        package shop

                        import dev.woge.host.WogeRegion
                        import dev.woge.html.HtmlWriter

                        class Cart(val items: List<String>)

                        @WogeRegion
                        fun HtmlWriter.cartSummary(cart: Cart) {
                            text("${'$'}{cart.items.size} items")
                        }
                        """.trimIndent(),
                ),
            )

        assertEquals(emptyList<String>(), result.errors)
        assertEquals(
            """
            // Generated by the Woge KSP processor from @WogeRegion cartSummary. Do not edit.
            package shop

            import shop.cartSummary as wogeRegionContent

            /** Region descriptor for [cartSummary]. Address it with `CartSummaryRegion.target(page)`. */
            public object CartSummaryRegion : dev.woge.host.PageRegion<shop.Cart>(
                name = "shop.cartSummary",
            ) {
                override fun render(
                    writer: dev.woge.html.HtmlWriter,
                    input: shop.Cart,
                ) {
                    writer.wogeRegionContent(input)
                }
            }

            """.trimIndent(),
            result.generated.getValue("CartSummaryRegion.kt"),
        )
    }

    @Test
    fun `component region keeps the key type and depends only on its own sources`() {
        val result = runKsp(TASK_ROW)

        assertEquals(emptyList<String>(), result.errors)
        assertEquals(
            """
            // Generated by the Woge KSP processor from @WogeRegion taskStatus. Do not edit.
            package tasks

            import tasks.taskStatus as wogeRegionContent

            /** Region descriptor for [taskStatus]. Address it with `TaskStatusRegion.target(page, key)`. */
            internal object TaskStatusRegion : dev.woge.host.KeyedRegion<tasks.TaskId, kotlin.collections.List<tasks.Label>?>(
                name = "tasks.taskStatus",
                component = "tasks.TaskRow",
            ) {
                override fun identityKey(key: tasks.TaskId): dev.woge.host.IdentityKey =
                    dev.woge.host.IdentityKey.of(key.value)

                override fun render(
                    writer: dev.woge.html.HtmlWriter,
                    input: kotlin.collections.List<tasks.Label>?,
                ) {
                    writer.wogeRegionContent(input)
                }
            }

            """.trimIndent(),
            result.generated.getValue("TaskStatusRegion.kt"),
        )
        assertEquals(
            RecordedDependencies(aggregating = false, originatingFiles = listOf("TaskRow.kt", "TaskStatus.kt")),
            result.dependencies.getValue("TaskStatusRegion.kt"),
        )
    }

    @Test
    fun `generation is byte-stable across runs`() {
        assertEquals(runKsp(TASK_ROW).generated, runKsp(TASK_ROW).generated)
    }

    private companion object {
        val TASK_ROW =
            mapOf(
                "TaskRow.kt" to
                    """
                    package tasks

                    import dev.woge.host.WogeComponent
                    import dev.woge.host.WogeKey

                    @JvmInline
                    value class TaskId(val value: Long)

                    @WogeComponent
                    class TaskRow(@WogeKey val id: TaskId, val title: String)
                    """.trimIndent(),
                "TaskStatus.kt" to
                    """
                    package tasks

                    import dev.woge.host.WogeRegion
                    import dev.woge.html.HtmlWriter

                    internal class Label(val text: String)

                    @WogeRegion(component = TaskRow::class)
                    fun HtmlWriter.taskStatus(labels: List<Label>?) {
                        labels?.forEach { text(it.text) }
                    }
                    """.trimIndent(),
            )
    }
}
