package dev.woge.ksp

import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Test

class RouteProcessorTest {
    @Test
    fun `route class generates url and decode for path and query values`() {
        val result = runKsp(PROJECT)

        assertEquals(emptyList<String>(), result.errors)
        assertEquals(
            """
            // Generated by the Woge KSP processor from @WogeRoute ProjectPageInput. Do not edit.
            package shop

            /** Route `/projects/{project}/tasks` for [ProjectPageInput]. Link with `ProjectPageRoute.url(input)`. */
            public object ProjectPageRoute : dev.woge.host.PageRoute<shop.ProjectPageInput>("/projects/{project}/tasks") {
                override fun url(input: shop.ProjectPageInput): dev.woge.html.ApplicationUrl =
                    buildUrl(
                        path = mapOf("project" to input.project.value),
                        query = listOf("view" to input.view?.let { dev.woge.host.RouteValues.format(it) }, "page" to input.page?.let { it.toString() }, "search" to input.search),
                    )

                override fun decode(parameters: dev.woge.host.RouteParameters): shop.ProjectPageInput =
                    shop.ProjectPageInput(
                        project = pathValue(parameters, "project") { shop.ProjectId(it) },
                        view = queryValue(parameters, "view") { dev.woge.host.RouteValues.enum<shop.View>(it) },
                        page = queryValue(parameters, "page") { it.toIntOrNull() },
                        search = queryValue(parameters, "search") { it },
                    )
            }

            """.trimIndent(),
            result.generated.getValue("ProjectPageRoute.kt"),
        )
        assertEquals(
            RecordedDependencies(aggregating = true, originatingFiles = listOf("Project.kt")),
            result.dependencies.getValue("ProjectPageRoute.kt"),
        )
    }

    @Test
    fun `object route has no parameters and keeps internal visibility`() {
        val result =
            runKsp(
                mapOf(
                    "Home.kt" to
                        """
                        package shop

                        import dev.woge.host.WogeRoute

                        @WogeRoute("/")
                        internal data object HomeInput
                        """.trimIndent(),
                ),
            )

        assertEquals(emptyList<String>(), result.errors)
        assertEquals(
            """
            // Generated by the Woge KSP processor from @WogeRoute HomeInput. Do not edit.
            package shop

            /** Route `/` for [HomeInput]. Link with `HomeRoute.url(input)`. */
            internal object HomeRoute : dev.woge.host.PageRoute<shop.HomeInput>("/") {
                override fun url(input: shop.HomeInput): dev.woge.html.ApplicationUrl =
                    buildUrl(
                        path = emptyMap(),
                        query = emptyList(),
                    )

                override fun decode(parameters: dev.woge.host.RouteParameters): shop.HomeInput =
                    shop.HomeInput
            }

            """.trimIndent(),
            result.generated.getValue("HomeRoute.kt"),
        )
    }

    @Test
    fun `literal and parameter segments may share a prefix`() {
        val result =
            runKsp(
                mapOf(
                    "Pages.kt" to
                        """
                        package shop

                        import dev.woge.host.WogeRoute

                        @WogeRoute("/projects/new")
                        data object NewProjectInput

                        @WogeRoute("/projects/{project}")
                        data class ProjectInput(val project: String)
                        """.trimIndent(),
                ),
            )

        assertEquals(emptyList<String>(), result.errors)
        assertEquals(setOf("NewProjectRoute.kt", "ProjectRoute.kt", "WogeDescriptors.kt"), result.generated.keys)
    }

    private companion object {
        val PROJECT =
            mapOf(
                "Project.kt" to
                    """
                    package shop

                    import dev.woge.host.WogeRoute

                    @JvmInline
                    value class ProjectId(val value: String)

                    enum class View { SHELL, COMPLETE }

                    @WogeRoute("/projects/{project}/tasks")
                    data class ProjectPageInput(
                        val project: ProjectId,
                        val view: View? = null,
                        val page: Int? = null,
                        val search: String? = null,
                    )
                    """.trimIndent(),
            )
    }
}
