package dev.woge.ksp

internal fun ActionModel.source(): String =
    """
    // Generated by the Woge KSP processor from @WogeAction $functionName. Do not edit.
    package $packageName

    /** Typed entry point for the native form action `$id`. */
    $visibility object $descriptorName : dev.woge.host.ActionDescriptor<$commandType>(dev.woge.host.ActionId.of("$id")) {
        override suspend fun execute(request: dev.woge.host.PageRequest<$commandType>): dev.woge.host.PageResult =
            $packageName.$functionName(request.input, request.context)
    }

    """.trimIndent()

internal fun List<ActionModel>.registrySource(packageName: String): String {
    val visibility = if (any { it.visibility == "internal" }) "internal" else "public"
    val entries = sortedBy { it.id }.joinToString(", ") { it.descriptorName }
    return """
        // Generated by the Woge KSP processor. Do not edit.
        package $packageName

        /** Explicit registry of this package's generated actions. */
        $visibility val wogeActions: dev.woge.host.ActionRegistry =
            dev.woge.host.ActionRegistry(listOf($entries))

        """.trimIndent()
}
