package dev.woge.ksp

/** Writes the Kotlin source of one generated region descriptor. The output is byte-stable. */
internal fun RegionModel.source(): String {
    val component = component
    val key = component?.key
    val supertype =
        if (key == null) {
            "dev.woge.host.PageRegion<$inputType>"
        } else {
            "dev.woge.host.KeyedRegion<${key.type}, $inputType>"
        }
    val names =
        listOfNotNull(
            "name = \"$identityName\"",
            component?.let { "component = \"${it.identityName}\"" },
        )
    val usage = if (key == null) "$descriptorName.target(page)" else "$descriptorName.target(page, key)"
    val packageLine = if (packageName.isEmpty()) "" else "package $packageName\n\n"
    val functionReference = if (packageName.isEmpty()) functionName else "$packageName.$functionName"
    return buildString {
        appendLine("// Generated by the Woge KSP processor from @WogeRegion $functionName. Do not edit.")
        append(packageLine)
        appendLine("import $functionReference as $CONTENT_ALIAS")
        appendLine()
        appendLine("/** Region descriptor for [$functionName]. Address it with `$usage`. */")
        appendLine("$visibility object $descriptorName : $supertype(")
        names.forEach { appendLine("    $it,") }
        appendLine(") {")
        if (key != null) {
            appendLine("    override fun identityKey(key: ${key.type}): dev.woge.host.IdentityKey =")
            appendLine("        dev.woge.host.IdentityKey.of(${key.argument})")
            appendLine()
        }
        appendLine("    override fun render(")
        appendLine("        writer: dev.woge.html.HtmlWriter,")
        appendLine("        input: $inputType,")
        appendLine("    ) {")
        appendLine("        writer.$CONTENT_ALIAS(input)")
        appendLine("    }")
        appendLine("}")
    }
}

private const val CONTENT_ALIAS = "wogeRegionContent"
