package dev.woge.ksp

/** Writes the Kotlin source of one generated route descriptor. The output is byte-stable. */
internal fun RouteModel.source(): String {
    val packageLine = if (packageName.isEmpty()) "" else "package $packageName\n\n"
    val simpleName = symbol.simpleName.asString()
    return buildString {
        appendLine("// Generated by the Woge KSP processor from @WogeRoute $simpleName. Do not edit.")
        append(packageLine)
        appendLine("/** Route `$path` for [$simpleName]. Link with `$descriptorName.url(input)`. */")
        appendLine("$visibility object $descriptorName : dev.woge.host.PageRoute<$inputType>(\"$path\") {")
        appendLine("    override fun url(input: $inputType): dev.woge.html.ApplicationUrl =")
        appendLine("        buildUrl(")
        appendLine("            path = ${pathValues()},")
        appendLine("            query = ${queryValues()},")
        appendLine("        )")
        appendLine()
        appendLine("    override fun decode(parameters: dev.woge.host.RouteParameters): $inputType =")
        if (isObject || parameters.isEmpty()) {
            appendLine("        $inputType${if (isObject) "" else "()"}")
        } else {
            appendLine("        $inputType(")
            parameters.forEach { appendLine("            ${it.name} = ${it.decoder()},") }
            appendLine("        )")
        }
        appendLine("}")
    }
}

private fun RouteModel.pathValues(): String {
    val values = parameters.filter { it.inPath }.map { "\"${it.name}\" to ${it.codec.format("input.${it.name}")}" }
    return if (values.isEmpty()) "emptyMap()" else values.joinToString(", ", "mapOf(", ")")
}

private fun RouteModel.queryValues(): String {
    val values =
        parameters.filterNot { it.inPath }.map {
            val formatted = it.codec.format("it")
            val value = if (formatted == "it") "input.${it.name}" else "input.${it.name}?.let { $formatted }"
            "\"${it.name}\" to $value"
        }
    return if (values.isEmpty()) "emptyList()" else values.joinToString(", ", "listOf(", ")")
}

private fun RouteParameterModel.decoder(): String {
    val read = if (inPath) "pathValue" else "queryValue"
    return "$read(parameters, \"$name\") { ${codec.parse} }"
}
