[versions]
coroutines = "1.11.0"
detekt = "1.23.8"
junit = "5.13.4"
junitPlatform = "1.13.4"
jmhGradle = "0.7.3"
jsoup = "1.23.2"
jetbrainsAnnotations = "26.1.0"
kotlin = "2.4.10"
ktlintGradle = "14.2.0"
serialization = "1.11.0"
springBoot = "4.1.1"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
jmh = { id = "me.champeau.jmh", version.ref = "jmhGradle" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }

[libraries]
assertjCore = { module = "org.assertj:assertj-core" }
detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
jakartaServletApi = { module = "jakarta.servlet:jakarta.servlet-api" }
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotations" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatform" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinxCoroutinesReactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlintGradlePlugin = { module = "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin", version.ref = "ktlintGradle" }
reactorNettyHttp = { module = "io.projectreactor.netty:reactor-netty-http" }
springBoot = { module = "org.springframework.boot:spring-boot" }
springBootAutoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure" }
springBootConfigurationProcessor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springBoot" }
springBootDependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }
springBootStarterWebflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }
springBootStarterWeb = { module = "org.springframework.boot:spring-boot-starter-web" }
springBootTest = { module = "org.springframework.boot:spring-boot-test" }
springContext = { module = "org.springframework:spring-context" }
springWebmvc = { module = "org.springframework:spring-webmvc" }
springWebflux = { module = "org.springframework:spring-webflux" }
