package dev.woge.development.orchestrator

import dev.woge.development.BuildId
import dev.woge.development.DevelopmentApplicationManifest
import dev.woge.development.DevelopmentChange
import dev.woge.development.DevelopmentDiagnostic
import dev.woge.development.DevelopmentUrl
import dev.woge.development.ExperimentalWogeDevelopmentApi
import dev.woge.development.ReloadLevel
import dev.woge.development.ServerExited
import dev.woge.development.ServerGeneration
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.emptyFlow

/**
 * Runs one build. Gradle, a Kotlin daemon or a test double can implement this port.
 *
 * The orchestrator cancels the coroutine when a newer edit supersedes the build, so implementations
 * must stop their work promptly on cancellation.
 */
@ExperimentalWogeDevelopmentApi
public fun interface DevelopmentBuildAdapter {
    public suspend fun build(request: DevelopmentBuildRequest): DevelopmentBuildResult
}

@ExperimentalWogeDevelopmentApi
public data class DevelopmentBuildRequest(
    public val buildId: BuildId,
    public val changes: Set<DevelopmentChange>,
)

@ExperimentalWogeDevelopmentApi
public sealed interface DevelopmentBuildResult {
    /** [requiredReload] is the cheapest level the build proves safe. The orchestrator may raise it. */
    public data class Succeeded(
        public val requiredReload: ReloadLevel = ReloadLevel.DOCUMENT_REFRESH,
    ) : DevelopmentBuildResult

    public data class Failed(
        public val diagnostics: List<DevelopmentDiagnostic>,
    ) : DevelopmentBuildResult {
        init {
            require(diagnostics.isNotEmpty()) { "A failed build must contain at least one structured diagnostic" }
        }
    }
}

/**
 * Owns the application child process. A Spring Boot adapter, a Ktor adapter or a test double can
 * implement this port.
 *
 * `restart` must keep the previous application running until the replacement is ready or the
 * requested level fails. It must be safe to call again after cancellation.
 */
@ExperimentalWogeDevelopmentApi
public interface DevelopmentHostAdapter {
    /** Unexpected exits of a ready child. Intentional stops must not emit here. */
    public val exits: Flow<ServerExited> get() = emptyFlow()

    public suspend fun restart(request: DevelopmentHostRestartRequest): DevelopmentHostRestartResult

    /** Stops the child process. Called once when the session ends and must not throw for a stopped child. */
    public suspend fun shutdown()
}

@ExperimentalWogeDevelopmentApi
public data class DevelopmentHostRestartRequest(
    public val buildId: BuildId,
    public val generation: ServerGeneration,
    public val level: ReloadLevel,
) {
    init {
        require(level.satisfies(ReloadLevel.SERVER_RESTART)) {
            "A host restart must use SERVER_RESTART or COLD_RESTART"
        }
    }
}

@ExperimentalWogeDevelopmentApi
public sealed interface DevelopmentHostRestartResult {
    public data class Ready(
        public val urls: List<DevelopmentUrl>,
    ) : DevelopmentHostRestartResult {
        init {
            require(urls.isNotEmpty()) { "A ready development server must expose at least one local URL" }
        }
    }

    /** The host cannot perform the requested level; the orchestrator tries the next safer level. */
    public data object Unsupported : DevelopmentHostRestartResult

    public data class Failed(
        public val diagnostics: List<DevelopmentDiagnostic>,
        public val previousApplicationRetained: Boolean,
    ) : DevelopmentHostRestartResult {
        init {
            require(diagnostics.isNotEmpty()) { "A failed restart must contain at least one structured diagnostic" }
        }
    }
}

/**
 * Applies browser-side levels below a server restart, such as a hot stylesheet update.
 *
 * Return `false` when the level is unsupported or uncertain; the orchestrator then uses the next
 * safer level. The browser channel itself observes [DevelopmentOrchestrator.events].
 */
@ExperimentalWogeDevelopmentApi
public fun interface DevelopmentFrontendAdapter {
    public suspend fun apply(
        buildId: BuildId,
        level: ReloadLevel,
    ): Boolean

    public companion object {
        /** Supports only a document refresh, which every browser can do without extra tooling. */
        public val documentRefreshOnly: DevelopmentFrontendAdapter =
            DevelopmentFrontendAdapter { _, level -> level == ReloadLevel.DOCUMENT_REFRESH }
    }
}

/** Reads the manifest generated by the build. The manifest schema itself is owned by its generator. */
@ExperimentalWogeDevelopmentApi
public fun interface DevelopmentManifestSource {
    public suspend fun manifest(buildId: BuildId): DevelopmentApplicationManifest?

    public companion object {
        public val none: DevelopmentManifestSource = DevelopmentManifestSource { null }
    }
}

/** The replaceable integrations of one development session. */
@ExperimentalWogeDevelopmentApi
public class DevelopmentAdapters(
    public val build: DevelopmentBuildAdapter,
    public val host: DevelopmentHostAdapter,
    public val frontend: DevelopmentFrontendAdapter = DevelopmentFrontendAdapter.documentRefreshOnly,
    public val manifest: DevelopmentManifestSource = DevelopmentManifestSource.none,
)
