package dev.woge.html

/** Per-response CSP nonce generated by the application and safe to place in a nonce attribute. */
@JvmInline
public value class CspNonce internal constructor(
    internal val value: String,
)

/** Browser-verified integrity metadata for an external stylesheet, script or preload. */
@JvmInline
public value class SubresourceIntegrity internal constructor(
    internal val value: String,
)

/** Standard CORS mode used by link and script elements. */
public enum class CrossOrigin(
    internal val htmlValue: String,
) {
    /** Send no credentials; the browser may send an Origin header. */
    ANONYMOUS("anonymous"),

    /** Include credentials when the server's CORS response permits them. */
    USE_CREDENTIALS("use-credentials"),
}

/**
 * Wraps a cryptographically random CSP nonce generated outside Woge for one response.
 *
 * Woge validates Base64/Base64URL shape but cannot verify randomness, uniqueness or entropy.
 */
public fun cspNonce(value: String): CspNonce {
    require(CSP_NONCE.matches(value)) { "CSP nonce must be a non-empty Base64 or Base64URL value" }
    return CspNonce(value)
}

/** Validates one or more SHA-256, SHA-384 or SHA-512 Subresource Integrity tokens. */
public fun subresourceIntegrity(value: String): SubresourceIntegrity {
    val tokens = value.split(ASCII_WHITESPACE).filter(String::isNotEmpty)
    require(tokens.isNotEmpty() && tokens.all(SRI_TOKEN::matches)) {
        "Subresource Integrity must contain valid sha256, sha384 or sha512 tokens"
    }
    return SubresourceIntegrity(tokens.joinToString(" "))
}

internal fun requireCrossOriginForExternalIntegrity(
    url: HtmlUrl,
    integrity: SubresourceIntegrity?,
    crossOrigin: CrossOrigin?,
) {
    require(integrity == null || url !is ExternalUrl || crossOrigin != null) {
        "Cross-origin assets with Subresource Integrity require an explicit crossorigin mode"
    }
}

private val CSP_NONCE: Regex = Regex("[A-Za-z0-9+/_-]+={0,2}")
private val SRI_TOKEN: Regex = Regex("sha(?:256|384|512)-[A-Za-z0-9+/_-]+={0,2}")
private val ASCII_WHITESPACE: Regex = Regex("[\\t\\n\\f\\r ]+")
