package dev.woge.host

/** Stable request identifier supplied or generated by the host adapter. */
@JvmInline
public value class RequestId private constructor(
    public val value: String,
) {
    public companion object {
        public fun of(value: String): RequestId {
            requireDiagnosticId(value, "Request ID")
            return RequestId(value)
        }
    }
}

/** Safe identifier that can be returned to a client and correlated with redacted server logs. */
@JvmInline
public value class CorrelationId private constructor(
    public val value: String,
) {
    public companion object {
        public fun of(value: String): CorrelationId {
            requireDiagnosticId(value, "Correlation ID")
            return CorrelationId(value)
        }
    }
}

/** A validated BCP 47-style language tag, or [UNDETERMINED]. */
@JvmInline
public value class LanguageTag private constructor(
    public val value: String,
) {
    public companion object {
        public val UNDETERMINED: LanguageTag = LanguageTag("und")

        public fun of(value: String): LanguageTag {
            require(value.length in 1..MAX_LANGUAGE_TAG_LENGTH && LANGUAGE_TAG.matches(value)) {
                "Language tag must use '-' separated ASCII letters and digits"
            }
            return LanguageTag(value)
        }
    }
}

/** Request and correlation identifiers established together at adapter ingress. */
public data class RequestTrace(
    public val requestId: RequestId,
    public val correlationId: CorrelationId,
)

/** Immutable request facts available to portable page code. */
public class RequestContext(
    public val method: RequestMethod,
    public val trace: RequestTrace,
    public val language: LanguageTag = LanguageTag.UNDETERMINED,
    public val headers: RequestHeaders = RequestHeaders.EMPTY,
    public val cookies: RequestCookies = RequestCookies.EMPTY,
    public val security: RequestSecurity = RequestSecurity(),
) {
    public val authentication: AuthenticationFacts
        get() = security.authentication

    public val csrf: CsrfVerification
        get() = security.csrf

    public val requestId: RequestId
        get() = trace.requestId

    public val correlationId: CorrelationId
        get() = trace.correlationId

    override fun toString(): String =
        "RequestContext(" +
            "method=${method.value}, " +
            "requestId=${requestId.value}, " +
            "correlationId=${correlationId.value}, " +
            "language=${language.value}, " +
            "headers=${headers.size}, " +
            "cookies=<redacted>, " +
            "authentication=${authentication.kind}, " +
            "csrf=$csrf)"
}

private fun requireDiagnosticId(
    value: String,
    label: String,
) {
    require(value.length in 1..MAX_DIAGNOSTIC_ID_LENGTH && value.all(::isDiagnosticIdCharacter)) {
        "$label must contain only ASCII letters, digits, '.', '_', ':', or '-'"
    }
}

private fun isDiagnosticIdCharacter(character: Char): Boolean =
    character in 'a'..'z' ||
        character in 'A'..'Z' ||
        character in '0'..'9' ||
        character == '.' ||
        character == '_' ||
        character == ':' ||
        character == '-'

private const val MAX_DIAGNOSTIC_ID_LENGTH: Int = 128
private const val MAX_LANGUAGE_TAG_LENGTH: Int = 64
private val LANGUAGE_TAG: Regex = Regex("[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*")
