package dev.woge.development.gradle

import dev.woge.development.ExperimentalWogeDevelopmentApi
import java.nio.file.Files
import java.nio.file.Path
import java.util.Properties

/**
 * Everything the `wogeDev` launcher needs, written by the Woge Gradle plugin into one properties file.
 *
 * Lists use numbered keys (`build.command.0`, `build.command.1`, ...) so paths with spaces stay intact.
 */
@ExperimentalWogeDevelopmentApi
public data class WogeDevelopmentSettings(
    public val projectDirectory: Path,
    public val stateDirectory: Path,
    public val buildCommand: List<String>,
    public val childJava: String,
    public val childClasspath: List<Path>,
    public val mainClassFile: Path,
    public val watchRoots: List<Path>,
    public val buildFiles: List<Path>,
    public val port: Int,
    public val fastRestart: Boolean = true,
    public val pollIntervalMillis: Long = DEFAULT_POLL_INTERVAL_MILLIS,
) {
    init {
        require(buildCommand.isNotEmpty()) { "The build command must not be empty" }
        require(childJava.isNotBlank()) { "The Java executable must not be blank" }
        require(port in 1..MAX_PORT) { "The application port must be between 1 and $MAX_PORT" }
        require(pollIntervalMillis > 0) { "The poll interval must be positive" }
    }

    /** The trigger file must sit in its own classpath directory, see ADR 0041. */
    public val triggerFile: Path get() = stateDirectory.resolve("trigger").resolve(".woge-restart-trigger")
    public val clientFile: Path get() = stateDirectory.resolve("client.properties")

    /**
     * The command for the application child. The main class comes from Spring Boot's
     * `resolveMainClassName` task, which runs in every development build.
     */
    public fun childCommand(mainClass: String): List<String> =
        listOf(
            childJava,
            "-Dwoge.development=true",
            "-cp",
            (childClasspath + triggerFile.parent).joinToString(java.io.File.pathSeparator),
            mainClass,
        )

    public fun writeTo(file: Path) {
        val properties = Properties()
        properties["project"] = projectDirectory.toString()
        properties["state"] = stateDirectory.toString()
        properties["port"] = port.toString()
        properties["fastRestart"] = fastRestart.toString()
        properties["pollInterval"] = pollIntervalMillis.toString()
        properties.putList("build.command", buildCommand)
        properties["child.java"] = childJava
        properties["child.mainClassFile"] = mainClassFile.toString()
        properties.putList("child.classpath", childClasspath.map(Path::toString))
        properties.putList("watch.root", watchRoots.map(Path::toString))
        properties.putList("watch.buildFile", buildFiles.map(Path::toString))
        Files.createDirectories(file.toAbsolutePath().parent)
        Files.newBufferedWriter(file).use { properties.store(it, "Generated by the Woge Gradle plugin") }
    }

    public companion object {
        public const val DEFAULT_POLL_INTERVAL_MILLIS: Long = 250
        private const val MAX_PORT = 65_535

        public fun readFrom(file: Path): WogeDevelopmentSettings {
            val properties = Properties()
            Files.newBufferedReader(file).use(properties::load)

            fun value(key: String): String = requireNotNull(properties.getProperty(key)) { "Missing setting '$key'" }
            return WogeDevelopmentSettings(
                projectDirectory = Path.of(value("project")),
                stateDirectory = Path.of(value("state")),
                buildCommand = properties.list("build.command"),
                childJava = value("child.java"),
                childClasspath = properties.list("child.classpath").map(Path::of),
                mainClassFile = Path.of(value("child.mainClassFile")),
                watchRoots = properties.list("watch.root").map(Path::of),
                buildFiles = properties.list("watch.buildFile").map(Path::of),
                port = value("port").toInt(),
                fastRestart = value("fastRestart").toBooleanStrict(),
                pollIntervalMillis = value("pollInterval").toLong(),
            )
        }

        private fun Properties.putList(
            key: String,
            values: List<String>,
        ) {
            values.forEachIndexed { index, item -> this["$key.$index"] = item }
        }

        private fun Properties.list(key: String): List<String> =
            generateSequence(
                0,
            ) { it + 1 }.map { getProperty("$key.$it") }.takeWhile { it != null }.map { it!! }.toList()
    }
}
