package dev.woge.development.gradle

import dev.woge.development.ExperimentalWogeDevelopmentApi
import java.nio.file.Files
import java.nio.file.Path
import java.util.Properties

/**
 * Everything the `wogeDev` launcher needs, written by the Woge Gradle plugin into one properties file.
 *
 * Lists use numbered keys (`build.command.0`, `build.command.1`, ...) so paths with spaces stay intact.
 */
@ExperimentalWogeDevelopmentApi
public data class WogeDevelopmentSettings(
    public val projectDirectory: Path,
    public val stateDirectory: Path,
    public val buildCommand: List<String>,
    public val childJava: String,
    public val childClasspath: List<Path>,
    public val mainClassFile: Path,
    public val watchRoots: List<Path>,
    public val buildFiles: List<Path>,
    public val port: Int,
    public val host: WogeDevelopmentHost = WogeDevelopmentHost.SPRING_BOOT,
    public val fastRestart: Boolean = true,
    public val pollIntervalMillis: Long = DEFAULT_POLL_INTERVAL_MILLIS,
    /** The Vite dev server to run next to the application; `null` without the `dev.woge.vite` plugin. */
    public val vite: ViteDevServerSettings? = null,
    /** Starts the experimental MCP endpoint for coding agents (ADR 0075). */
    public val mcp: Boolean = false,
    /** The MCP port; 0 picks a free port. */
    public val mcpPort: Int = 0,
) {
    init {
        require(buildCommand.isNotEmpty()) { "The build command must not be empty" }
        require(childJava.isNotBlank()) { "The Java executable must not be blank" }
        require(port in 1..MAX_PORT) { "The application port must be between 1 and $MAX_PORT" }
        require(pollIntervalMillis > 0) { "The poll interval must be positive" }
        require(mcpPort in 0..MAX_PORT) { "The MCP port must be between 0 and $MAX_PORT" }
    }

    /** The trigger file must sit in its own classpath directory, see ADR 0041. */
    public val triggerFile: Path get() = stateDirectory.resolve("trigger").resolve(".woge-restart-trigger")
    public val clientFile: Path get() = stateDirectory.resolve("client.properties")

    /** Where coding agents find the MCP URL and token while `wogeDev --mcp` runs. */
    public val mcpFile: Path get() = stateDirectory.resolve("mcp.json")

    /** Written by the `wogeManifest` task. */
    public val manifestFile: Path get() = projectDirectory.resolve(".woge").resolve("manifest.json")

    /**
     * The command for the application child. For Spring Boot the main class comes from
     * `resolveMainClassName`; for Ktor it comes from the `application` plugin's `mainClass`.
     */
    public fun childCommand(mainClass: String): List<String> {
        // Path is Iterable<Path>; `+ path` would add its name segments instead of the directory.
        val triggerDirectory = listOf(triggerFile.parent)
        val classpath =
            if (host ==
                WogeDevelopmentHost.SPRING_BOOT
            ) {
                childClasspath + triggerDirectory
            } else {
                childClasspath
            }
        return listOf(
            childJava,
            "-Dwoge.development=true",
            "-cp",
            classpath.joinToString(java.io.File.pathSeparator),
            mainClass,
        )
    }

    public fun writeTo(file: Path) {
        val properties = Properties()
        properties["project"] = projectDirectory.toString()
        properties["state"] = stateDirectory.toString()
        properties["port"] = port.toString()
        properties["host"] = host.id
        properties["fastRestart"] = fastRestart.toString()
        properties["pollInterval"] = pollIntervalMillis.toString()
        properties["mcp"] = mcp.toString()
        properties["mcp.port"] = mcpPort.toString()
        properties.putList("build.command", buildCommand)
        properties["child.java"] = childJava
        properties["child.mainClassFile"] = mainClassFile.toString()
        properties.putList("child.classpath", childClasspath.map(Path::toString))
        properties.putList("watch.root", watchRoots.map(Path::toString))
        properties.putList("watch.buildFile", buildFiles.map(Path::toString))
        vite?.let {
            properties.putList("vite.command", it.command)
            properties["vite.directory"] = it.directory.toString()
            properties["vite.port"] = it.port.toString()
            properties.putList("vite.env", it.environment.map { (key, value) -> "$key=$value" })
        }
        Files.createDirectories(file.toAbsolutePath().parent)
        Files.newBufferedWriter(file).use { properties.store(it, "Generated by the Woge Gradle plugin") }
    }

    public companion object {
        public const val DEFAULT_POLL_INTERVAL_MILLIS: Long = 250
        private const val MAX_PORT = 65_535

        public fun readFrom(file: Path): WogeDevelopmentSettings {
            val properties = Properties()
            Files.newBufferedReader(file).use(properties::load)

            fun value(key: String): String = requireNotNull(properties.getProperty(key)) { "Missing setting '$key'" }
            return WogeDevelopmentSettings(
                projectDirectory = Path.of(value("project")),
                stateDirectory = Path.of(value("state")),
                buildCommand = properties.list("build.command"),
                childJava = value("child.java"),
                childClasspath = properties.list("child.classpath").map(Path::of),
                mainClassFile = Path.of(value("child.mainClassFile")),
                watchRoots = properties.list("watch.root").map(Path::of),
                buildFiles = properties.list("watch.buildFile").map(Path::of),
                port = value("port").toInt(),
                host = WogeDevelopmentHost.of(properties.getProperty("host") ?: WogeDevelopmentHost.SPRING_BOOT.id),
                fastRestart = value("fastRestart").toBooleanStrict(),
                pollIntervalMillis = value("pollInterval").toLong(),
                mcp = properties.getProperty("mcp")?.toBooleanStrict() ?: false,
                mcpPort = properties.getProperty("mcp.port")?.toInt() ?: 0,
                vite =
                    properties.list("vite.command").takeIf { it.isNotEmpty() }?.let { command ->
                        ViteDevServerSettings(
                            command = command,
                            directory = Path.of(value("vite.directory")),
                            port = value("vite.port").toInt(),
                            environment =
                                properties.list("vite.env").associate {
                                    it.substringBefore('=') to it.substringAfter('=')
                                },
                        )
                    },
            )
        }

        private fun Properties.putList(
            key: String,
            values: List<String>,
        ) {
            values.forEachIndexed { index, item -> this["$key.$index"] = item }
        }

        private fun Properties.list(key: String): List<String> =
            generateSequence(
                0,
            ) { it + 1 }.map { getProperty("$key.$it") }.takeWhile { it != null }.map { it!! }.toList()
    }
}

/** How `wogeDev` starts the project's own Vite dev server (ADR 0070). */
@ExperimentalWogeDevelopmentApi
public data class ViteDevServerSettings(
    public val command: List<String>,
    public val directory: Path,
    public val port: Int,
    public val environment: Map<String, String> = emptyMap(),
) {
    init {
        require(command.isNotEmpty()) { "The Vite command must not be empty" }
        require(port in 1..MAX_PORT) { "The Vite port must be between 1 and 65535" }
    }

    /** The loopback origin that pages load `@vite/client` and the entry modules from. */
    public val origin: String get() = "http://127.0.0.1:$port"

    private companion object {
        const val MAX_PORT = 65_535
    }

    override fun toString(): String = "ViteDevServerSettings(port=$port, directory=$directory, environment=<redacted>)"
}

/** The server framework that `wogeDev` starts as a child process. */
@ExperimentalWogeDevelopmentApi
public enum class WogeDevelopmentHost(
    public val id: String,
    internal val displayName: String,
    internal val mainClassHint: String,
) {
    SPRING_BOOT(
        "spring-boot",
        "Spring Boot",
        "Add a class with @SpringBootApplication and a main function, or set springBoot.mainClass.",
    ),
    KTOR(
        "ktor",
        "Ktor",
        "Set application.mainClass in your Gradle build.",
    ),
    ;

    public companion object {
        public fun of(id: String): WogeDevelopmentHost =
            requireNotNull(entries.firstOrNull { it.id == id }) {
                "Unknown development host '$id'. Use one of: ${entries.joinToString { it.id }}"
            }
    }
}
